.TH pdfatfi 1 "2019-11-24"
.SH NAME
pdfatfi \- Help program for the LaTeX package attachfile2.
.SH SYNOPSIS
pdfatfi <command> [<options>] <file[.atfi]>]
.SH DESCRIPTION
Helper program for the LaTeX package attachfile2.

This package also tries to get and add meta information data,
such as file size, file date, checksum, ....

The script pdfatfi.pl is provided for use with old versions of
pdfTeX and XeTeX that do not provide access
to  file metadata.

The use of the Perl script is not mandatory. This data can be shown
by PDF viewers, but they are not a requirement of the PDF specification.

Package attachfile2 and the Perl script communicate
via an auxiliary file with file extension .atfi. The script
is used between two LaTeX runs and updates the auxiliary file.

.nf
latex test
pdfatfi test
latex test
dvips test
ps2pdf test.ps test.pdf
.fi

.SH OPTIONS
Various options are supported
.IP --help
Show help text.
.IP --version
Print version number
.IP --(no)quiet
Suppress/don't suppress messages
.IP --(no)verbose
Verbose (not verbose) printing.
.IP --(no)debug
Debug infomation printed (not printed)
.SH BUGS
Please log issues on the GitHub homepage:
.br
https://github.com/ho-tex/attachfile2/issues.
.SH AUTHOR
Heiko Oberdiek (ho-tex@tug.org)
.SH SEE ALSO
See attachfile2.pdf for more details.
